### PR TITLE
Merge of linuxboot/mainboards into linuxboot/linuxboot

### PR DESCRIPTION
**Pull request by rjoleary**
This is very rudimentary and lot of cleanup has to happen in follow ups.

### CODE REVIEW

**Comment by rjoleary** [comment]
For #47

**Comment by synackd** [comment]
@rjoleary Do we want a complete `tianocore/ovmf` (waiting on upstream patch for EDK2 patch for 16MiB OVMF build sizes) to be a part of this PR?

**Comment by rjoleary** [comment]
> @rjoleary Do we want a complete `tianocore/ovmf` (waiting on upstream patch for EDK2 patch for 16MiB OVMF build sizes) to be a part of this PR?

Send your patch to github.com/linuxboot/mainboards for now. There is still a lot to do to clean this up.

I migrated the patches over with `git format-patch --root HEAD`, copied over all the *.patch files, and ran `git am --directory=mainboards *.patch`. We can take a second pass at this for future commits.

**Comment by rjoleary** [comment]
I have done my best to preserve history.

Here is the DCO error message:

```
Commit sha: 4f3c83a, Author: Ronald G. Minnich, Committer: Ryan O'Leary; Expected "Ronald G. Minnich rminnich@gmail.com", but got "Lennon zhongswag@gmail.com".
Commit sha: dacac18, Author: vejmarie, Committer: Ryan O'Leary; Can not find "vejmarie vejmarie@users.noreply.github.com", in ["Jean-marie Verdun vejmarie@Jean-maries-MacBook-Air.local", "Jean-marie Verdun vejmarie@Jean-maries-MacBook-Air.local"].
Commit sha: 0d5f7e3, Author: vejmarie, Committer: Ryan O'Leary; Expected "vejmarie vejmarie@users.noreply.github.com", but got "Jean-Marie Verdun jean-marie.verdun@hpe.com".
Commit sha: 27ec7eb, Author: Devon Bautista, Committer: Ryan O'Leary; Expected "Devon Bautista devontbautista@gmail.com", but got "Devon Bautista dbautista@newmexicoconsortium.org".
```

Here are those commits in order:

1. https://github.com/linuxboot/linuxboot/pull/48/commits/4f3c83aa87aaad5c075106c1e25d15f8b8641b59
2. https://github.com/linuxboot/linuxboot/pull/48/commits/dacac187976563a6e80cb7a937194b6f301c9d18
3. https://github.com/linuxboot/linuxboot/pull/48/commits/0d5f7e34a56fa271c21f4922cd452480e91ed1c0
4. https://github.com/linuxboot/linuxboot/pull/48/commits/27ec7eb1cfe95024c272f91e356b5de52977cfed

2, 3, and 4 have an author which does not match the signed-off line. On visual inspection, the authors match and only differ by email. This is okay.

I will have to ask Ron what happened for 1.

**Comment by rjoleary** [comment]
This is good for approval. The idea is common parts of the Makefile and the CI system integrated in follow-up PRs.

**Review by rminnich — APPROVED** [review]

**Pull request merged**
